# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           "/:title"

# Setup
title:               WINSTON LARSON
tagline:             Managing innovation
url:                 http://winstonlarson.com/
paginate:            5
baseurl:             "http://winstonlarson.com/"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Winston Larson
  url:               http://winstonlason.com
  email:             winstonlarson@gmail.com

pages_list:
  About: '/about'
  Archive: '/archive'
  Resume: '/resume'
  Portfolio: '/portfolio'

# Custom vars
version:             2.0.0
github:              https://github.com/winstonlarson
  # repo:              https://github.com/winstonlarson/winstonlarson.github.io

# Conversion
markdown: kramdown
kramdown:
  input: GFM
